export default {
	LOADING: 'LOADING',
	SHOWINTRO: 'SHOWINTRO',
	LANGUAGECODE: 'LANGUAGECODE',
	SHOWMODAL: 'SHOWMODAL',
	SHOWMODALPLUS: 'SHOWMODALPLUS',
	RESETSTATE: 'RESETSTATE',

	SIGNUP : 'SIGNUP',
	SIGNIN : 'SIGNIN',
	LOGOUT : 'LOGOUT',
	FORGOTPASSWORD : 'FORGOTPASSWORD',
	ONLINE_STATUS: 'ONLINE_STATUS',

	USER_ONLINE: 'USER_ONLINE',
	USER_OFFLINE: 'USER_OFFLINE',
};